public enum EventKeys
{
    PLAYER_MOVED,
    PLAYER_JUMPED,
    PLAYER_GRAPPLE_PULLED,
    PLAYER_GRAPPLED,
    PLAYER_GRAPPLE_RELEASED,
    PLAYER_LANDED,
    TERRAIN_GENERATION_REQUESTED,
    TERRAIN_GENERATION_COMPLETED,
}